services:
  backend:
    build:
      context: ./backend
    container_name: backendChat
    ports:
     - "3000:3000"
     - "3001:3001"
    environment:
      - DATABASE_HOST=database
      - DATABASE_PORT=5432
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=232332321
      - DATABASE_NAME=chat
    volumes:
      - ./uploads:/usr/src/app/uploads
    networks:
      - app-network
  
  frontend:
    build:
      context: ./frontend
    container_name: frontendChat
    ports:
      - "8080:8080"
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: npm run dev
    networks:
      - app-network

  database:
    image: postgres:13
    container_name: postgresChat
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 232332321
      POSTGRES_DB: chat
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  pgdata: